# Generated by Django 4.2.7 on 2024-09-25 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
            ],
        ),
        migrations.AddField(
            model_name='parentmod',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.codemod', verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='teachermod',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.codemod', verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='usermod',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.codemod', verbose_name='Code'),
        ),
    ]
