# Generated by Django 4.2.7 on 2024-09-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_usermod_parents_alter_usermod_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermod',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.parentmod', verbose_name='Parents'),
        ),
        migrations.AlterField(
            model_name='usermod',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teachermod', verbose_name='Teachers'),
        ),
    ]
