# Generated by Django 4.2.7 on 2024-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_codemod_parentmod_code_teachermod_code_usermod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_user_data',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='teacher_name'),
        ),
    ]
