# Generated by Django 4.2.7 on 2024-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_save_user_data_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmod',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='save_user_data',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='teachermod',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='usermod',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code'),
        ),
        migrations.DeleteModel(
            name='CodeMod',
        ),
    ]
