# Generated by Django 4.2.7 on 2024-09-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_usermod_parents_alter_usermod_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentmod',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Tolov'),
        ),
        migrations.AddField(
            model_name='teachermod',
            name='payment',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tolov'),
        ),
    ]
