# Generated by Django 4.2.7 on 2024-09-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_parentmod_payment_teachermod_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_user_data',
            name='un_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Un_id'),
        ),
    ]
